apiVersion: v1
kind: ConfigMap
metadata:
  name: cicdproject-config
  namespace: cicdproject
data:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "ecommerce"
  DATABASE_USER: "ecommerce"
