"""add product stock

Revision ID: e582403d8732
Revises: 177e35ad2f80
Create Date: 2026-08-21 11:17:12.270095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e582403d8732'
down_revision: Union[str, Sequence[str], None] = '177e35ad2f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "products",
        sa.Column("stock", sa.Integer(), nullable=True)
    )

    op.execute(
        "UPDATE products SET stock = 0 WHERE stock IS NULL"
    )

    op.alter_column(
        "products",
        "stock",
        nullable=False
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock')
    # ### end Alembic commands ###
